export const TEAM_CREATING = 'TEAM_CREATING';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_ERROR = 'TEAM_CREATE_ERROR';
export const TEAM_REQUESTING = 'TEAM_REQUESTING';
export const TEAM_REQUEST_SUCCESS = 'TEAM_REQUEST_SUCCESS';
export const TEAM_REQUEST_ERROR = 'TEAM_REQUEST_ERROR';
