export const SET_USER = 'SET_USER';
export const USER_REQUESTING = 'USER_REQUESTING';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR';
