appli:
  image: tdlf/back:1.0
  container_name: tdlf_back
  restart: always
  volumes:
    - /home/etna/Documents/etna/tdlf/TapeDansLeFond/TDLF/back/appli:/var/www/html
    - /home/etna/Documents/etna/tdlf/sql:/var/lib/mysql
  ports:
    - 9500:80
    - 222:22
  working_dir: /var/www/html
