appli:
  image: tdlf/back:3
  container_name: tdlf_back
  restart: always
  volumes:
    - /home/etna/Documents/etna/tdlf/TapeDansLeFond/TDLF/back/appli:/var/www/html
  ports:
    - 9500:80
  working_dir: /var/www/html
  links:
    - "db"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: tdlf_pma
  restart: always
  ports:
    - 9501:80
  environment:
    - PMA_HOST=db
  links:
    - "db"
db:
  image: mysql
  container_name: tdlf_sql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 2d74VSGwvMtop4f
  volumes:
    - /home/etna/Documents/etna/tdlf/sql:/var/lib/mysql
    - /home/etna/Documents/etna/tdlf/TapeDansLeFond/TDLF/back/config/my.cnf:/etc/my.cnf
