appli:
  image: tdlf/back:latest
  container_name: tdlf_back
  restart: always
  volumes:
    - ../appli:/var/www/html
    - /ETNA/ETNA_Master1/GPE/sql:/var/lib/mysql
  ports:
    - 9500:80
  working_dir: /var/www/html